# Generated by Django 3.1 on 2020-09-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotw', '0003_auto_20200916_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='audioDB_artistID',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
