# Generated by Django 3.1 on 2020-09-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotw', '0002_album_nomination_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='audioDB_albumID',
            field=models.PositiveIntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='aotw_date',
            field=models.DateField(blank=True, null=True, verbose_name='date as AOTW'),
        ),
    ]
